### ISSUE TITLE
Mojave Developer Beta support

### ISSUE THREAD

**Issue by ArtikusHG** [lvs1974/IntelGraphicsFixup#10]
Hey there, Ivs1974.

It seems like the IntelGraphicsFixup driver does not support macOS 10.14 (Mojave). Are you considering updating it now or when the release is out?

My Intel SkyLake (HD 520) Graphics card doesn't seem to work: I cannot boot with the proper platform-id (191B0000) even though I've rebuilt kext caches and double checked that Lilu and its plugins inject fine. I can only boot (with 8 MB video memory) if my platform-id is 12345678.

I can attach the liludbg log but there's nothing interesting there.

Sincerely, ArtikusHG.

**Comment by vandroiy2013** [comment]
Add -lilubetaall in Boot->Arguments in config.plist
