### ISSUE TITLE
Suggestion about add IntelHDMI FakeID Function.

### ISSUE THREAD

**Issue by gujiangjiang** [lvs1974/IntelGraphicsFixup#2]
Hello lvs1974.

I suggest add Intel HDMI Audio Fake function to IntelGraphicsFixup.

I found some laptop such as DELL XPS or Xiaomi Book have problem and cant boot into macOS sometimes when lack FakePCIID + FakePCIID_Intel_HDMI_Audio.

But i dont want to any fakepciid kexts so i want to merge this function to intelgraphicsfixup to solve this problem.

https://bitbucket.org/RehabMan/os-x-fake-pci-id/src/3c51b8fe84155b8c8ecc7c9b08db5d3575f6f46f/injectors/Intel_HDMI_Audio.plist?at=master&fileviewer=file-view-default

thanks.

**Comment by vit9696** [comment]
There is no need in FakePCIID for HDMI audio, it is enough to just use AppleALC for this matter. What Rehabman did is an unnecessary complication/confusion/inadequate decision.

Furthermore, HDMI audio cannot prevent macOS from booting, so check your config and avoid messing it up. Be aware that tonymac DSDT "fixing" manual quality is unfortunately terrible, and you could very easily bork your ACPI by following them.

**Comment by gujiangjiang** [comment]
@vit9696 

I have test many month and i am sure it related with HDMI Audio to prevet boot into macOS but not always.

If i delete FakePCIID and FakeIntelHDMIAudio it with prevent boot sometimes but restart can boot again.

If add FakePCIID and FakeIntelHDMIAudio then it with no problem and i used half a year and with no problem.

Yesterday i found IntelGraphicsFixup updated and seem to add some HDMI support so i tried again with new IntelGraphicsFixup and delelte 2 Fake Kexts but still come about prevent boot after many time reboot and i add Fake kexts it became well and have no problem.

This problem i have posted in AppleALC but closed and i have talked to PMHeart and she can confirm this problem.

If you dont believe you can ask other XPS users no matter XPS159550 of XPS159560 it all have this problem.

I give this suggestion is aim to delete any FakePCIID kexts because i think these kexts are not reliable but it must use this kexts to aviod some problem so i suggest add it to this kext such as AppleBrcmFixup add FakeID support.

Thanks for your reply.

**Comment by gujiangjiang** [comment]
Clover Add HDMI or IntelHDMI have no use with Skylake HDMI audio support because XPS HDMI use different ID so it cant be recognized by macOS so it may use FakePCIID to attatch this ID to macOS to support native HDMi support to prevent boot problem sometimes.

**Comment by gujiangjiang** [comment]
Here are the reason why it must use FakePCIID to support some HDMI devices.

> FakePCIID_Intel_HDMI_Audio.kext: This kext will attach to 8086:0c0c or 8086:9d70 or 8086:a170
The purpose is to provide support for unsupported HDAU (usually called B0D3, but renamed to HDAU to match what Apple expects) devices which provide HDMI-audio on Haswell(+) systems. 8086:0c0c is the unsupported ID. The other two 8086:0d0c, and 8086:0a0c are supported. This kext, AppleHDAController, loads by PCI class, so you normally would not inject device-id for it, but to allow FakePCIID to work, you may need to inject RM,device-id (one of the supported IDs). By default, the kext injects RM,device-id=<0c 0a 00 00> (0x0a0c). You can override it with a DSDT edit.

**Comment by vit9696** [comment]
Look, if it was an incorrect device id, then it would always fail. All you say here is an unfortunate nonsense. I don't know what PMHeart said, but so far I have seen tons of absolutely bizarre and inadequate setups, and their authors always try to convince me that they do it just right. And these people for some reason find an issue tracker something similar to the support forum. In my opinion, if you are not a developer and are not 200% sure, then never ever write here.

In my opinion, disable clover GPU/Audio inject, most of ACPI fixes, and all the other mess you did. Like FakeXXX kexts and similar garbage.

Just inject the necessary ig-platform-id and a device-id (if your IGPU is not natively supported) via Arbitrary into your IGPU. IntelGraphicsFixup and AppleALC will do everything else automatically on their own.

To get HDMI work you might have to patch the device-id in AppleHDAController, but most likely AppleALC already has it. To reduce you confusion you can attach the lspci output or preboot.log here, and somebody from the team could confirm/add a patch in AppleALC.

**Comment by gujiangjiang** [comment]
Not fail..........

I dont say any fail anymore.

I said if dont use these 2 kexts then it will accidently prevent boot into macOS and i dont have HDMI devices so i dont know if HDMI works or not,

I always said it was related to HDMI and may prevent boot in some times.

I dont use any Clover GPU or Audio Injection and i only use SSDT-IGPU and SSDT-HDEF to inject GPU and HDMI.

Because this problem i have discussed with XPS15 and XPS13 users and all have this problem no matter use SSDT or Clover to inject this.

I'm confused same with you and i dont why cause this problem but it test it was HDMI problem.Everytime AppleALC add HDMI support or IntelGraphicsFixup add HDMI support i will test again but still cant solve this problem.

Here are another XPS user use FakeHDMI to solve boot problem.
https://github.com/darkhandz/XPS15-9550-Sierra/commit/5930a3a906c64740304c95b0bbe335890d02a72a

> 测了几天，补上FakePCIID_Intel_HDMI_Audio.kext即可解决开机卡Logo的问题（这回真的不卡了）
Endglish

> Test a few days, Add FakePCIID_Intel_HDMI_Audio.kext to solve the issue of prevent boot in Apple  Logo (this time is really no problem)

Here are my boot.log.

[bootlog.log.txt](https://github.com/lvs1974/IntelGraphicsFixup/files/1802877/bootlog.log.txt)

Very thanks for your work for hackintosh.

**Comment by vandroiy2013** [comment]
Your controller is NATIVE.

> 0:104  0:000  PCI (00|00:1F.03) : 8086 A170 class=040380

So you don't need any FakePCIID or something...
As @vit9696 told you earlier the problem obviously is in your ACPI/config.plist

**Comment by gujiangjiang** [comment]
@vandroiy2013 

Thanks for your reply.
I dont know why i must use FakeHDMI but when i dont use these 2 kexts it will accidently cant boot and stop in boot progress 2/3.

Here are my all the config + ACPI +Kexts.

I have tried my best to give up FakePCIID and FakeIntelHDMIAudio but still no use.

**Comment by gujiangjiang** [comment]
[XPS 15 9550.zip](https://github.com/lvs1974/IntelGraphicsFixup/files/1802983/XPS.15.9550.zip)

**Comment by gujiangjiang** [comment]
Here are rehabman saying.

> In the case of Skylake 8086:9d70 or 8086:1a70, it is attaching to the HDEF device (usually called HDAS, but renamed to HDEF to match what Aple expects). Skylake HDMI/DP audio codec is on HDEF along with onboard audio. It injects RM,device-id=<70 a1 00 00> for 0x9d70 and RM,device-id=<70 9d 00 00> for 0xa170. In other words, with these two device-ids, it will reverse them.

**Comment by vit9696** [comment]
@RehabMan, could you please clarify the intions of the quoted patches? It feels either a misinterpretation or a common misbelief.

**Comment by gujiangjiang** [comment]
But i still dont know why lack FakeHDMI it will prevent boot in sometimes.

**Comment by RehabMan** [comment]
@vit9696, which "quoted patches" are you referring to?  The only recent "quoted patches" (in @gujiangjiang's post) are related to HDEF, not IGPU.

Note that some of the things FakePCIID_Intel_HD_Graphics.kext (and FakePCIID_Intel_HDMI_Audio.kext) are doing are historical and support previous versions of macOS/OS X where such support was NOT native.

**Comment by vit9696** [comment]
Well, in particular the https://github.com/lvs1974/IntelGraphicsFixup/issues/2#issuecomment-372316784 part. What is the reason for swapping the identifiers between each other?

**Comment by gujiangjiang** [comment]
@RehabMan

Hello RehabMan.
My Laptop must use FakePCIID and FakeHDMI to aviod boot fail in sometimes with no omen and occasionally and i dont why cause this problem.
I have test half a year and together with other XPS users to test this and confirm it if add FakePCIID and FakeIntelHDMIAudio it have no boot problem.

**Comment by RehabMan** [comment]
> Well, in particular the #2 (comment) part. What is the reason for swapping the identifiers between each other?

I don't know what you mean by #2..., but I assume you're referring to the quote that @gujiangjiang made...

On some computers, some versions of macOS/OS X, it enables HDMI audio (and for some it will break working HDMI audio!)
Some even require injecting a different spoof-id (via RM,device-id).
It is purely trial/error.

**Comment by vit9696** [comment]
Well, we both know that audio initialisation is a deterministic thing. What you describe cannot be completely denied but each such case needs to be properly investigated and a more scientific solution is to be found.

@gujiangjiang in my opinion, you should go to the forums and either learn or let somebody with more knowledge fix the setup for you. Currently it simply makes no sense, and for this reason I won't add crazy stuff neither to igfx, nor to applealc.

**Comment by gujiangjiang** [comment]
First I must say thanks to all of you for the hard work for us.

I will continue to use fakepciid and fakehdmi to avoid problem temporary until I find the real reason about this problem and I will post here when I figure out what happed.

Thanks again.

**Comment by RehabMan** [comment]
> Well, we both know that audio initialisation is a deterministic thing. What you describe cannot be completely denied but each such case needs to be properly investigated and a more scientific solution is to be found.

If you have the hardware that reproduces the problem, perhaps you can do such work...

**Comment by al3xtjames** [comment]
Perhaps `AppleHDAController::controllerSpecificFeatures` may have something to do with it?

```c++
__int64 __fastcall AppleHDAController::controllerSpecificFeatures(AppleHDAController *this)
{
  AppleHDAController *v1; // rbx
  __int64 v2; // rdi
  IOPCIDevice *v3; // r14
  __int64 v4; // rax
  __int64 v5; // rax
  int v6; // ecx
  __int64 result; // rax
  int v8; // eax
  signed __int64 v9; // rdx

  v1 = this;
  v2 = *this->gap98;
  if ( !v2 )
  {
    v9 = 0x2B01LL;
    return IOLog("Sound assertion in %s at line %d\n", "AppleHDAController", v9);
  }
  v3 = OSMetaClassBase::safeMetaCast(v2, IOPCIDevice::metaClass);
  if ( !v3 )
  {
    v9 = 0x2B04LL;
    return IOLog("Sound assertion in %s at line %d\n", "AppleHDAController", v9);
  }
  /* "hda-idle-support" property present in MacBookPro14,x HDEF */
  v4 = (*(**v1->gap98 + 696LL))(*v1->gap98, "hda-idle-support");
  v5 = OSMetaClassBase::safeMetaCast(v4, OSData::metaClass);
  v6 = v1->field_ED4;
  if ( v6 == kPCIDeviceID_SunrisePoint_LP_HDA /* 0x9D70 */ || v5
    || v6 == kPCIDeviceID_KabyLake_LP_HDA /* 0x9D71 */ )
    v1[2].gap98[41] = 1;
  result = v6 & 0xFFFFFFFE;
  if ( result == kPCIDeviceID_SunrisePoint_LP_HDA /* 0x9D70 */ )
    v1[2].gap98[40] = 1;
  if ( v6 == kPCIDeviceID_SunrisePoint_H_HDA /* 0xA170 */ && !v1[2].gap98[41] )
  {
    IOPCIDevice::extendedConfigWrite32(v3, 0x44uLL, 0x1Bu);
    /* 0x48 = INTEL_HDA_CGCTL? */
    result = IOPCIDevice::extendedConfigWrite32(v3, 0x48uLL, 0);
  }
  if ( v1[2].gap98[41] )
  {
    v8 = IOPCIDevice::extendedConfigRead32(v3, 0x48uLL);
    result = IOPCIDevice::extendedConfigWrite32(v3, 0x48uLL, v8 & 0xFFFFFFBF);
  }
  return result;
}
```

**Comment by gujiangjiang** [comment]
@al3xtjames How to do this?

**Comment by vit9696** [comment]
@al3xtjames if faking hdmi to 0x9D70 works just fine, then why not to add an AppleALC patch to replace 0x9D70 by 0xA171 for 0xA171 device-id? It kind of feels a most natural solution to my eyes.
