### ISSUE TITLE
Broke my hackintosh

### ISSUE THREAD

**Issue by c0h1b4** [lvs1974/IntelGraphicsFixup#3]
Just replaced the 1.2.4 with the latest 1.2.6 and it broke my system. Can’t boot anymore :(

I have the following system

Motherboard: GA-H270N-WIFI
CPU: i5 7600

Clover v.4411

High Sierra 10.13.3

I just downgraded the kext manually and I can’t boot anymore. It looks like it destroyed the graphics part on my hackintosh.

**Comment by vit9696** [comment]
Мы гуляли по Неглинной, заходили на бульвар, нам купили синий-синий, презелёный красный шар.
