### ISSUE TITLE
Update 10.11.6

### ISSUE THREAD

**Issue by kimmansur** [lvs1974/IntelGraphicsFixup#7]
Hello,
I'm having some issues with my intelgraphics, yesterday my mac updated to a new security update, but i had change some parameters in AppleIntelSNBGraphics.kext for increase the size of memory by the intelgraphics, but i didn't saw this update. Your fixup could solve this issue?

i used this:
From 512mb to 1GB:
"cd /S*/L*/Ext*/AppleIntelSNBGraphicsFB.kext/C*/M*

sudo cp AppleIntelSNBGraphicsFB AppleIntelSNBGraphicsFB.backup

sudo perl -pi -e 's|\xC7\x45\xBC\x00\x00\x00\x20|\xc7\x45\xBC\x00\x00\x00\x40|g' AppleIntelSNBGraphicsFB

sudo touch /S*/L*/Extensions

Add These Lines in the Info.plist at AppleIntelHD3000Graphics.kext/C*
Have to add after VRAMOverrride the VRAMSize key, it will be like this:
<key>VRAMOverride</key>
<integer>0</integer>
<key>VRAMSize</key>
<integer>1024</integer>"
I already tried to replace the file but with no sucess!

**Comment by vit9696** [comment]
You may refer to https://github.com/lvs1974/IntelGraphicsFixup/blob/master/IntelFramebuffer.bt regarding the framebuffer structure. The rest is out of the scope.
