### ISSUE TITLE
igfxfw=1 seems to cause iGPU problems after wake?

### ISSUE THREAD

**Issue by canyondust** [lvs1974/IntelGraphicsFixup#9]
I'm using IntelGraphicsFixup to enable quicksync, main video card is GTX1080. After wake from sleep, programs that use quicksync hang. Removing the boot arg igfxfw=1 fixes the problem.

Here is some log output at the time of launching VLC after wake from sleep:

fault 16:48:23.865219 -0400 kernel void IOAccelEventMachine2::signalHardwareError(eRestartRequest, int32_t): GPURestartSignaled stampIdx=1 type=3 prevType=0 numStamps=9
fault 16:48:23.865225 -0400 kernel void IOAccelEventMachine2::signalHardwareError(eRestartRequest, int32_t): GPURestartEnqueued stampIdx=1 type=3
fault 16:48:23.865230 -0400 kernel void IOAccelEventMachine2::hardwareErrorEvent(): setting restart type to 3 (channel 1)
fault 16:48:23.865231 -0400 kernel void IOAccelEventMachine2::hardwareErrorEvent(): GPURestartDequeued stampIdx=1 type=3
fault 16:48:23.896083 -0400 kernel void IOAccelEventMachine2::restart_channel(): GPURestartSkipped stampIdx=1 type=3
fault 16:48:23.896088 -0400 kernel void IOAccelEventMachine2::restart_channel(): no channel associated with stamp_idx 1 (type 3)
fault 16:48:24.896750 -0400 kernel virtual void IOAccelEventMachineFast2::checkGPUProgress() - Signaling hardware error on channel 1..
fault 16:48:24.896757 -0400 kernel void IOAccelEventMachine2::signalHardwareError(eRestartRequest, int32_t): GPURestartSignaled stampIdx=1 type=2 prevType=0 numStamps=9
fault 16:48:24.896759 -0400 kernel void IOAccelEventMachine2::signalHardwareError(eRestartRequest, int32_t): GPURestartEnqueued stampIdx=1 type=2
fault 16:48:24.896763 -0400 kernel void IOAccelEventMachine2::hardwareErrorEvent(): setting restart type to 2 (channel 1)
fault 16:48:24.896765 -0400 kernel void IOAccelEventMachine2::hardwareErrorEvent(): GPURestartDequeued stampIdx=1 type=2
fault 16:48:24.926953 -0400 kernel void IOAccelEventMachine2::restart_channel(): GPURestartSkipped stampIdx=1 type=2
fault 16:48:24.926956 -0400 kernel void IOAccelEventMachine2::restart_channel(): no channel associated with stamp_idx 1 (type 2)

**Comment by vit9696** [comment]
Hi, it is unfortunately a problem in Apple's drivers, and not much could be done until they fix it.
